-- Early warning panel, part 1 of 3: the rulebook table.
-- One row per indicator: what it measures, the exact amber and red rules, and why it matters.
-- The numbers in amber_level / red_level are the ones the view (part 2) uses, so to change a threshold
-- you edit this table only. The *_rule text columns must be kept in step by hand when you do.
-- Run once in the BigQuery console (it replaces the table).

CREATE OR REPLACE TABLE `project-e042f011-a587-4cbe-8f7.Market_Data_Project.ew_indicators`
OPTIONS (description = 'Early warning panel: one row per indicator with its amber/red thresholds and plain-English rules. Edit thresholds here; vw_early_warning reads them.')
AS
SELECT * FROM UNNEST([
  STRUCT(
    'R1' AS indicator_id, 10 AS sort, 'Rates' AS area, 'US yield curve' AS name, 'pts' AS unit,
    'US 10-year Treasury yield minus the 3-month Treasury bill yield (FRED T10Y3M).' AS what_it_measures,
    0.25 AS amber_level, 0.0 AS red_level,
    'Amber: below +0.25 (flat) or inverted (below zero).' AS amber_rule,
    'Red: has turned positive again in the last 6 months after being inverted for 60+ days in the last 2 years.' AS red_rule,
    'An inverted curve has come before every US recession since the 1960s, usually 6-18 months ahead. The most dangerous stretch has historically been when it turns positive again, as the central bank starts cutting.' AS why_it_matters,
    'FRED (Federal Reserve Bank of St. Louis)' AS source_note),
  STRUCT('R2', 20, 'Rates', 'UK yield curve', 'pts',
    '10-year gilt yield minus Bank Rate (Bank of England series IUDMNPY minus IUDBEDR).',
    0.25, 0.0,
    'Amber: below +0.25 (flat) or inverted (below zero).',
    'Red: has turned positive again in the last 6 months after being inverted for 60+ days in the last 2 years.',
    'The UK version of the same signal. Bank Rate stands in for the short end; a long stretch below zero means money is tight relative to growth expectations.',
    'Bank of England'),
  STRUCT('C1', 30, 'Credit', 'US junk-bond spread', '%',
    'Extra yield investors demand to hold US high-yield (junk) bonds over Treasuries (ICE BofA index, FRED BAMLH0A0HYM2).',
    4.5, 6.0,
    'Amber: above 4.5%, or up 1.0 point or more in 3 months.',
    'Red: above 6.0%, or up 2.0 points or more in 3 months.',
    'Bond investors are often first to flinch: spreads widened months before the 2007 and 2022 share falls. The speed of widening matters as much as the level.',
    'FRED (ICE BofA)'),
  STRUCT('J1', 40, 'Jobs', 'US Sahm rule', 'pts',
    'Three-month average US unemployment rate minus its lowest three-month average in the previous 12 months (FRED SAHMREALTIME).',
    0.30, 0.50,
    'Amber: 0.30 or more.',
    'Red: 0.50 or more (the recession trigger).',
    'Has flagged every US recession since 1970 at or near its start. It is a confirmation signal more than an early one, but it rarely gives false alarms.',
    'FRED'),
  STRUCT('J2', 50, 'Jobs', 'UK unemployment (Sahm-style)', 'pts',
    'UK unemployment rate (ONS MGSX, already a three-month average) minus its lowest level in the previous 12 months.',
    0.30, 0.50,
    'Amber: 0.30 or more.',
    'Red: 0.50 or more.',
    'The same rule applied to UK figures. UK data is revised and noisier than US data, so treat a single month with care.',
    'Office for National Statistics'),
  STRUCT('J3', 60, 'Jobs', 'US jobless claims', '%',
    'Four-week average of new US unemployment claims, measured against its lowest point in the past year (FRED ICSA).',
    15.0, 25.0,
    'Amber: 15% or more above its 12-month low.',
    'Red: 25% or more above its 12-month low.',
    'Weekly and timely: a sustained rise from the low has preceded recent recessions by a few months.',
    'FRED (US Department of Labor)'),
  STRUCT('S1', 70, 'Stress', 'VIX (US fear index)', 'level',
    'Expected 30-day volatility of the S&P 500, priced from options (FRED VIXCLS).',
    22.0, 30.0,
    'Amber: 22 or more.',
    'Red: 30 or more.',
    'Moves with the market rather than ahead of it, so it says how stressed things are now. A low VIX alongside the other warnings means complacency.',
    'FRED (Cboe)'),
  STRUCT('V1', 80, 'Valuation', 'Buffett indicator (US)', '%',
    'Market value of US company shares divided by US GDP (FRED NCBEILQ027S / GDP), rolled forward daily with the S&P 500 since the last quarterly figure.',
    90.0, NULL,
    'Amber: in the top 10% of its readings since 2005.',
    'Never red: valuation says how far there is to fall, not when.',
    'High readings have meant poor returns over the following decade, but the market can stay expensive for years. Context for how hard a fall could be, not a timing signal.',
    'FRED (Federal Reserve Z.1, Bureau of Economic Analysis)'),
  STRUCT('B1', 90, 'Breadth', 'US equal-weight vs market-cap', 'pts',
    'Six-month return of the average S&P 500 stock (equal weight) minus the S&P 500 index (market-cap weight), from our own prices.',
    -5.0, -10.0,
    'Amber: the average stock trails the index by 5 points or more over 6 months.',
    'Red: trails by 10 points or more.',
    'When a few giant companies carry the index while the typical stock lags, the rally is narrow and more fragile.',
    'Own price data (fact_daily_prices, hist_prices_20y_us)'),
  STRUCT('B2', 100, 'Breadth', 'UK stocks above 200-day average', '%',
    'Share of FTSE 100 and FTSE 250 stocks trading above their own 200-day average price, from our own prices.',
    40.0, 25.0,
    'Amber: fewer than 40% (bottom fifth of readings since 2005).',
    'Red: fewer than 25% (bottom tenth of readings since 2005).',
    'A falling share while the FTSE 100 holds up means fewer companies are doing the lifting.',
    'Own price data (fact_daily_prices, hist_prices_20y)'),
  STRUCT('D1', 110, 'Volume', 'FTSE 100 distribution days', 'days',
    'Days in the last 25 sessions when the FTSE 100 fell 0.2% or more on higher volume than the day before.',
    8.0, 10.0,
    'Amber: 8 or more (top tenth of readings since 2005).',
    'Red: 10 or more (top 3% of readings since 2005).',
    'Heavy-volume down days suggest big investors are selling into strength. A cluster has often come before a correction.',
    'Own index data (hist_index_20y)'),
  STRUCT('D2', 120, 'Volume', 'S&P 500 distribution days', 'days',
    'Days in the last 25 sessions when the S&P 500 fell 0.2% or more on higher volume than the day before.',
    8.0, 10.0,
    'Amber: 8 or more (top tenth of readings since 2005).',
    'Red: 10 or more (top 3% of readings since 2005).',
    'As above, for the US market.',
    'Own index data (hist_index_20y)')
]);
